SELECT CAIXA.DS_CAIXA
      ,MOV_CAIXA.CD_MOV_CAIXA
      ,MOV_CAIXA.CD_LOTE_CAIXA
      ,DOC_CAIXA.NR_DOCUMENTO
      ,DOC_CAIXA.DS_DOCUMENTO
      ,MOV_CAIXA.DS_MOV_CAIXA
      ,To_Char(MOV_CAIXA.DT_MOVIMENTACAO,'DD/MM/YYYY HH24:MI') DT_MOVIMENTACAO
      ,Decode(MOV_CAIXA.TP_MOVIMENTACAO,'E','RECEITA'
                                      ,'S','DESPESA') TP_MOVIMENTACAO
      ,MOV_CAIXA.VL_MOVIMENTACAO
      ,To_Char(DOC_CAIXA.DT_VENCIMENTO,'DD/MM/YYYY HH24:MI') DT_VENCIMENTO
      ,MOV_CAIXA.CD_REDUZIDO
      ,PLANO_CONTAS.CD_CONTABIL
      ,PLANO_CONTAS.DS_CONTA
      ,MOV_CAIXA.CD_LAN_CONCOR
      ,LAN_CONCOR.DS_LAN_CONCOR
      ,MOV_CAIXA.CD_SETOR
      ,SETOR.NM_SETOR
      ,MOV_CAIXA.TP_ORIGEM_MOV
      ,MOV_CAIXA.CD_PROCESSO
      ,PROCESSO.CD_ESTRUTURAL
      ,PROCESSO.DS_PROCESSO
      ,MOV_CAIXA.CD_MOTIVO_LCTO
      ,MOTIVO_LCTO.DS_MOTIVO_LCTO

FROM MOV_CAIXA, PLANO_CONTAS, PROCESSO, DOC_CAIXA, LAN_CONCOR, MOTIVO_LCTO, SETOR, CAIXA

WHERE MOV_CAIXA.CD_DOC_CAIXA = DOC_CAIXA.CD_DOC_CAIXA(+)
AND MOV_CAIXA.CD_REDUZIDO = PLANO_CONTAS.CD_REDUZIDO(+)
AND MOV_CAIXA.CD_SETOR = SETOR.CD_SETOR(+)
AND MOV_CAIXA.CD_PROCESSO = PROCESSO.CD_PROCESSO(+)
AND MOV_CAIXA.CD_MOTIVO_LCTO = MOTIVO_LCTO.CD_MOTIVO_LCTO(+)
AND MOV_CAIXA.CD_LAN_CONCOR = LAN_CONCOR.CD_LAN_CONCOR(+)
AND DOC_CAIXA.CD_CAIXA = CAIXA.CD_CAIXA(+)
AND MOV_CAIXA.DT_MOVIMENTACAO BETWEEN '01/02/2017' AND '31/03/2017'
--AND DOC_CAIXA.NR_DOCUMENTO = '850216'      
