SELECT CD_USUARIO_AGEND         CD_USUARIO_AGEND
      ,USUARIO_AGENDAMENTO      USUARIO_AGENDAMENTO
      ,Nvl(SETOR_ATENDIMENTO,'AGENDAMENTOS NÃO ATENDIDOS')    SETOR_ATENDIMENTO
      ,Count(CD_MARCACAO)       QTD_AGEND_ATEND
      ,COMPETENCIA              COMPETENCIA


FROM (

SELECT ATENDIME.CD_ATENDIMENTO                  ATENDIMENTO
      ,ATENDIME.CD_PACIENTE                     PRONTUARIO
      ,PACIENTE.NM_PACIENTE                     PACIENTE
      ,IT_MARCACAO.CD_MARCACAO                  CD_MARCACAO
      ,TIP_MAR.DS_TIP_MAR                       TIP_MARCACAO
      ,SER_DIS.DS_SER_DIS                       DES_SERVICO
      ,Decode(IT_MARCACAO.SN_ENCAIXE,'S','SIM'
                                    ,'N','NAO') SN_ENCAIXE
      ,IT_MARCACAO.NM_USUARIO                   CD_USUARIO_AGEND
      ,DBASGU.USUARIOS.NM_USUARIO               USUARIO_AGENDAMENTO
      ,ORI_ATE.DS_ORI_ATE                       SETOR_ATENDIMENTO
      ,To_Char(IT_MARCACAO.DT_AGENDADO,'MM/YYYY')  COMPETENCIA

FROM IT_MARCACAO, PACIENTE, ATENDIME, TIP_MAR, SER_DIS, ORI_ATE, DBASGU.USUARIOS

WHERE Trunc(IT_MARCACAO.DT_AGENDADO) BETWEEN '01/09/2016' AND '31/03/2017'
AND IT_MARCACAO.CD_SER_DIS = SER_DIS.CD_SER_DIS(+)
AND IT_MARCACAO.CD_TIP_MAR = TIP_MAR.CD_TIP_MAR(+)
AND IT_MARCACAO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO(+)
AND ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE(+)
AND ATENDIME.CD_ORI_ATE = ORI_ATE.CD_ORI_ATE(+) 
AND IT_MARCACAO.NM_USUARIO = DBASGU.USUARIOS.CD_USUARIO
--AND IT_MARCACAO.NM_USUARIO = 'CELIA'       )
)
GROUP BY SETOR_ATENDIMENTO
       , CD_USUARIO_AGEND
       ,USUARIO_AGENDAMENTO
       , COMPETENCIA

ORDER BY 2 ASC  
